#ifndef __GLOBAL_H__
#define __GLOBAL_H__

#include <freefare.h>

#define SPACEBIAPPID 0x031337
#define SPACEBIAPPKEYNUM 12
#define SPACEBITRANSACTIONHISTORY 10

#define CURRENTAPPSTRUCTUREVERSION 0x0000

#define KEYNO_APPMASTER       0
#define KEYNO_PUBLICACCESS    1
#define KEYNO_PERSONALINFO    2
#define KEYNO_DOORREADER      3
#define KEYNO_LDAPINFO        4
#define KEYNO_RANDOMUID1      5
#define KEYNO_RANDOMUID2      6
#define KEYNO_RANDOMUID3      7
#define KEYNO_RANDOMUID4      8
#define KEYNO_CREDIT_RW       9
#define KEYNO_CREDIT_RD      10
#define KEYNO_CREDIT_WR      11

#define FILENO_METADATA      1
#define FILENO_PERSONALINFO  2
#define FILENO_DOORINFO      11
#define FILENO_LDAPINFO      12
#define FILENO_RANDOMUID1    21
#define FILENO_RANDOMUID2    22
#define FILENO_RANDOMUID3    23
#define FILENO_RANDOMUID4    24
#define FILENO_CREDITMETA    31
#define FILENO_CREDITS       32
#define FILENO_TRANSACTIONS  33

//                                 READ                WRITE            READ/WRITE       CHANGEOPTIONS
#define FACCESS_METADATA      MDAR(KEYNO_PUBLICACCESS, KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_PERSONALINFO  MDAR(KEYNO_PERSONALINFO, KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_DOORINFO      MDAR(KEYNO_DOORREADER,   KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_LDAPINFO      MDAR(KEYNO_LDAPINFO,     KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_RANDOMUID1    MDAR(KEYNO_RANDOMUID1,   KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_RANDOMUID2    MDAR(KEYNO_RANDOMUID2,   KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_RANDOMUID3    MDAR(KEYNO_RANDOMUID3,   KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_RANDOMUID4    MDAR(KEYNO_RANDOMUID4,   KEYNO_APPMASTER, KEYNO_APPMASTER, KEYNO_APPMASTER)
#define FACCESS_CREDITMETA    MDAR(KEYNO_CREDIT_RD,    KEYNO_CREDIT_WR, KEYNO_CREDIT_RW, KEYNO_CREDIT_RW)
#define FACCESS_CREDITS       MDAR(KEYNO_CREDIT_RD,    KEYNO_CREDIT_WR, KEYNO_CREDIT_RW, KEYNO_CREDIT_RW)
#define FACCESS_TRANSACTIONS  MDAR(KEYNO_CREDIT_RD,    KEYNO_CREDIT_WR, KEYNO_CREDIT_RW, KEYNO_CREDIT_RW)


#endif