#ifndef __GLOBAL_H__
#define __GLOBAL_H__

#define SPACEBIAPPID 0x031337

#define KEYNO_APPMASTER   0
#define KEYNO_DOORREADER  1
#define KEYNO_LDAPINFO    2
#define KEYNO_RANDOMUID1  3
#define KEYNO_RANDOMUID2  4

#define FILENO_METADATA   1
#define FILENO_DOORINFO   2
#define FILENO_LDAPINFO   3
#define FILENO_RANDOMUID1 4
#define FILENO_RANDOMUID2 5

#endif